### ISSUE TITLE
Could this be solved by creating a pull request to original API

### ISSUE THREAD

**Issue by aasaru** [Luceos/OnApp#1]
Hi!

Thanks for the project! Just what I was looking for.

I was wondering if this problem - making original library available to Composer projects could be solved by creating a pull request to original Wrapper project. This pull request would only contain one new file - composer.json addded to the root of the project.

So my question is - would adding this file to original project do the trick or would it be required for the owners of the project to change other files as well. I see you have moved all the code into src directory. Also you suggest that small changes have been made in code. Would everything work without it as well?

My point is that if I was maintainer of the original Wrapper and if all it woud take to make my project composer compatible would be one additional file in my code base then I would accept the file to my repository. Have you tried that?

Thanks for the trouble.
Juhan

**Comment by luceos** [comment]
> making original library available to Composer projects could be solved by creating a pull request to original Wrapper project

there is a pull request already to make the package composer ready, the maintainer still did not support it though

> would adding this file to original project do the trick or would it be required for the owners of the project to change other files as well

yes that works, the author of the PR to support composer did the same thing

The reason why I did not add simply the composer file is because I needed to add the code required for our own applications. This includes the recipes function and a function to migrate disks between datastores. For this reason we included a fork in the src directory. If you don't need those fixes you can simply add a composer file and point to the same directory to identify as autoloader source directory.

> Have you tried that?

So yes, I actually did that, it's also possible.

**Comment by aasaru** [comment]
Thanks for the reply. I see the pull request is there, sorry i didn't notice it earlier.
